// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Vbs3GetPos.proto

package com.artistech.vbs3;

public final class Vbs3Protos {
  private Vbs3Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VBS3.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 1;</code>
     */
    float getX();

    /**
     * <code>required float y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 2;</code>
     */
    float getY();

    /**
     * <code>required float z = 3;</code>
     */
    boolean hasZ();
    /**
     * <code>required float z = 3;</code>
     */
    float getZ();

    /**
     * <code>optional float deltaT = 4;</code>
     */
    boolean hasDeltaT();
    /**
     * <code>optional float deltaT = 4;</code>
     */
    float getDeltaT();

    /**
     * <code>optional string id = 5;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 5;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 5;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required float dir = 6;</code>
     */
    boolean hasDir();
    /**
     * <code>required float dir = 6;</code>
     */
    float getDir();

    /**
     * <code>required float worldCenterX = 7;</code>
     */
    boolean hasWorldCenterX();
    /**
     * <code>required float worldCenterX = 7;</code>
     */
    float getWorldCenterX();

    /**
     * <code>required float worldCenterY = 8;</code>
     */
    boolean hasWorldCenterY();
    /**
     * <code>required float worldCenterY = 8;</code>
     */
    float getWorldCenterY();

    /**
     * <code>optional string lat = 9;</code>
     */
    boolean hasLat();
    /**
     * <code>optional string lat = 9;</code>
     */
    java.lang.String getLat();
    /**
     * <code>optional string lat = 9;</code>
     */
    com.google.protobuf.ByteString
        getLatBytes();

    /**
     * <code>optional string lon = 10;</code>
     */
    boolean hasLon();
    /**
     * <code>optional string lon = 10;</code>
     */
    java.lang.String getLon();
    /**
     * <code>optional string lon = 10;</code>
     */
    com.google.protobuf.ByteString
        getLonBytes();
  }
  /**
   * Protobuf type {@code VBS3.Position}
   */
  public static final class Position extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VBS3.Position)
      PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Position(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Position defaultInstance;
    public static Position getDefaultInstance() {
      return defaultInstance;
    }

    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              x_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              y_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              z_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              deltaT_ = input.readFloat();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              id_ = bs;
              break;
            }
            case 53: {
              bitField0_ |= 0x00000020;
              dir_ = input.readFloat();
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              worldCenterX_ = input.readFloat();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              worldCenterY_ = input.readFloat();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              lat_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              lon_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.artistech.vbs3.Vbs3Protos.internal_static_VBS3_Position_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.artistech.vbs3.Vbs3Protos.internal_static_VBS3_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.artistech.vbs3.Vbs3Protos.Position.class, com.artistech.vbs3.Vbs3Protos.Position.Builder.class);
    }

    public static com.google.protobuf.Parser<Position> PARSER =
        new com.google.protobuf.AbstractParser<Position>() {
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Position(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>required float x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>required float y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private float z_;
    /**
     * <code>required float z = 3;</code>
     */
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float z = 3;</code>
     */
    public float getZ() {
      return z_;
    }

    public static final int DELTAT_FIELD_NUMBER = 4;
    private float deltaT_;
    /**
     * <code>optional float deltaT = 4;</code>
     */
    public boolean hasDeltaT() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float deltaT = 4;</code>
     */
    public float getDeltaT() {
      return deltaT_;
    }

    public static final int ID_FIELD_NUMBER = 5;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 5;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string id = 5;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIR_FIELD_NUMBER = 6;
    private float dir_;
    /**
     * <code>required float dir = 6;</code>
     */
    public boolean hasDir() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required float dir = 6;</code>
     */
    public float getDir() {
      return dir_;
    }

    public static final int WORLDCENTERX_FIELD_NUMBER = 7;
    private float worldCenterX_;
    /**
     * <code>required float worldCenterX = 7;</code>
     */
    public boolean hasWorldCenterX() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required float worldCenterX = 7;</code>
     */
    public float getWorldCenterX() {
      return worldCenterX_;
    }

    public static final int WORLDCENTERY_FIELD_NUMBER = 8;
    private float worldCenterY_;
    /**
     * <code>required float worldCenterY = 8;</code>
     */
    public boolean hasWorldCenterY() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required float worldCenterY = 8;</code>
     */
    public float getWorldCenterY() {
      return worldCenterY_;
    }

    public static final int LAT_FIELD_NUMBER = 9;
    private java.lang.Object lat_;
    /**
     * <code>optional string lat = 9;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string lat = 9;</code>
     */
    public java.lang.String getLat() {
      java.lang.Object ref = lat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lat_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lat = 9;</code>
     */
    public com.google.protobuf.ByteString
        getLatBytes() {
      java.lang.Object ref = lat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LON_FIELD_NUMBER = 10;
    private java.lang.Object lon_;
    /**
     * <code>optional string lon = 10;</code>
     */
    public boolean hasLon() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string lon = 10;</code>
     */
    public java.lang.String getLon() {
      java.lang.Object ref = lon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lon_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lon = 10;</code>
     */
    public com.google.protobuf.ByteString
        getLonBytes() {
      java.lang.Object ref = lon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      x_ = 0F;
      y_ = 0F;
      z_ = 0F;
      deltaT_ = 0F;
      id_ = "";
      dir_ = 0F;
      worldCenterX_ = 0F;
      worldCenterY_ = 0F;
      lat_ = "";
      lon_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDir()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWorldCenterX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWorldCenterY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, z_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, deltaT_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeFloat(6, dir_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, worldCenterX_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, worldCenterY_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getLatBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getLonBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, z_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, deltaT_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, dir_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, worldCenterX_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, worldCenterY_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getLatBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getLonBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.artistech.vbs3.Vbs3Protos.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.artistech.vbs3.Vbs3Protos.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.artistech.vbs3.Vbs3Protos.Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VBS3.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VBS3.Position)
        com.artistech.vbs3.Vbs3Protos.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.artistech.vbs3.Vbs3Protos.internal_static_VBS3_Position_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.artistech.vbs3.Vbs3Protos.internal_static_VBS3_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.artistech.vbs3.Vbs3Protos.Position.class, com.artistech.vbs3.Vbs3Protos.Position.Builder.class);
      }

      // Construct using com.artistech.vbs3.Vbs3Protos.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        deltaT_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        dir_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000020);
        worldCenterX_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        worldCenterY_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        lat_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        lon_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.artistech.vbs3.Vbs3Protos.internal_static_VBS3_Position_descriptor;
      }

      public com.artistech.vbs3.Vbs3Protos.Position getDefaultInstanceForType() {
        return com.artistech.vbs3.Vbs3Protos.Position.getDefaultInstance();
      }

      public com.artistech.vbs3.Vbs3Protos.Position build() {
        com.artistech.vbs3.Vbs3Protos.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.artistech.vbs3.Vbs3Protos.Position buildPartial() {
        com.artistech.vbs3.Vbs3Protos.Position result = new com.artistech.vbs3.Vbs3Protos.Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deltaT_ = deltaT_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.dir_ = dir_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.worldCenterX_ = worldCenterX_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.worldCenterY_ = worldCenterY_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.lon_ = lon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.artistech.vbs3.Vbs3Protos.Position) {
          return mergeFrom((com.artistech.vbs3.Vbs3Protos.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.artistech.vbs3.Vbs3Protos.Position other) {
        if (other == com.artistech.vbs3.Vbs3Protos.Position.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        if (other.hasDeltaT()) {
          setDeltaT(other.getDeltaT());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000010;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasDir()) {
          setDir(other.getDir());
        }
        if (other.hasWorldCenterX()) {
          setWorldCenterX(other.getWorldCenterX());
        }
        if (other.hasWorldCenterY()) {
          setWorldCenterY(other.getWorldCenterY());
        }
        if (other.hasLat()) {
          bitField0_ |= 0x00000100;
          lat_ = other.lat_;
          onChanged();
        }
        if (other.hasLon()) {
          bitField0_ |= 0x00000200;
          lon_ = other.lon_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasZ()) {
          
          return false;
        }
        if (!hasDir()) {
          
          return false;
        }
        if (!hasWorldCenterX()) {
          
          return false;
        }
        if (!hasWorldCenterY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.artistech.vbs3.Vbs3Protos.Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.artistech.vbs3.Vbs3Protos.Position) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>required float x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }

      private float z_ ;
      /**
       * <code>required float z = 3;</code>
       */
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float z = 3;</code>
       */
      public float getZ() {
        return z_;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder setZ(float value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float z = 3;</code>
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0F;
        onChanged();
        return this;
      }

      private float deltaT_ ;
      /**
       * <code>optional float deltaT = 4;</code>
       */
      public boolean hasDeltaT() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float deltaT = 4;</code>
       */
      public float getDeltaT() {
        return deltaT_;
      }
      /**
       * <code>optional float deltaT = 4;</code>
       */
      public Builder setDeltaT(float value) {
        bitField0_ |= 0x00000008;
        deltaT_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float deltaT = 4;</code>
       */
      public Builder clearDeltaT() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deltaT_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 5;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string id = 5;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 5;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 5;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 5;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }

      private float dir_ ;
      /**
       * <code>required float dir = 6;</code>
       */
      public boolean hasDir() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required float dir = 6;</code>
       */
      public float getDir() {
        return dir_;
      }
      /**
       * <code>required float dir = 6;</code>
       */
      public Builder setDir(float value) {
        bitField0_ |= 0x00000020;
        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float dir = 6;</code>
       */
      public Builder clearDir() {
        bitField0_ = (bitField0_ & ~0x00000020);
        dir_ = 0F;
        onChanged();
        return this;
      }

      private float worldCenterX_ ;
      /**
       * <code>required float worldCenterX = 7;</code>
       */
      public boolean hasWorldCenterX() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required float worldCenterX = 7;</code>
       */
      public float getWorldCenterX() {
        return worldCenterX_;
      }
      /**
       * <code>required float worldCenterX = 7;</code>
       */
      public Builder setWorldCenterX(float value) {
        bitField0_ |= 0x00000040;
        worldCenterX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float worldCenterX = 7;</code>
       */
      public Builder clearWorldCenterX() {
        bitField0_ = (bitField0_ & ~0x00000040);
        worldCenterX_ = 0F;
        onChanged();
        return this;
      }

      private float worldCenterY_ ;
      /**
       * <code>required float worldCenterY = 8;</code>
       */
      public boolean hasWorldCenterY() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required float worldCenterY = 8;</code>
       */
      public float getWorldCenterY() {
        return worldCenterY_;
      }
      /**
       * <code>required float worldCenterY = 8;</code>
       */
      public Builder setWorldCenterY(float value) {
        bitField0_ |= 0x00000080;
        worldCenterY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float worldCenterY = 8;</code>
       */
      public Builder clearWorldCenterY() {
        bitField0_ = (bitField0_ & ~0x00000080);
        worldCenterY_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object lat_ = "";
      /**
       * <code>optional string lat = 9;</code>
       */
      public boolean hasLat() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string lat = 9;</code>
       */
      public java.lang.String getLat() {
        java.lang.Object ref = lat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lat_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lat = 9;</code>
       */
      public com.google.protobuf.ByteString
          getLatBytes() {
        java.lang.Object ref = lat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lat = 9;</code>
       */
      public Builder setLat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lat = 9;</code>
       */
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lat_ = getDefaultInstance().getLat();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lat = 9;</code>
       */
      public Builder setLatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lat_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lon_ = "";
      /**
       * <code>optional string lon = 10;</code>
       */
      public boolean hasLon() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string lon = 10;</code>
       */
      public java.lang.String getLon() {
        java.lang.Object ref = lon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lon_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lon = 10;</code>
       */
      public com.google.protobuf.ByteString
          getLonBytes() {
        java.lang.Object ref = lon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lon = 10;</code>
       */
      public Builder setLon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        lon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lon = 10;</code>
       */
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000200);
        lon_ = getDefaultInstance().getLon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lon = 10;</code>
       */
      public Builder setLonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        lon_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VBS3.Position)
    }

    static {
      defaultInstance = new Position(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VBS3.Position)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VBS3_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VBS3_Position_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Vbs3GetPos.proto\022\004VBS3\"\232\001\n\010Position\022\t\n" +
      "\001x\030\001 \002(\002\022\t\n\001y\030\002 \002(\002\022\t\n\001z\030\003 \002(\002\022\016\n\006deltaT" +
      "\030\004 \001(\002\022\n\n\002id\030\005 \001(\t\022\013\n\003dir\030\006 \002(\002\022\024\n\014world" +
      "CenterX\030\007 \002(\002\022\024\n\014worldCenterY\030\010 \002(\002\022\013\n\003l" +
      "at\030\t \001(\t\022\013\n\003lon\030\n \001(\tB \n\022com.artistech.v" +
      "bs3B\nVbs3Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_VBS3_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VBS3_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VBS3_Position_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "DeltaT", "Id", "Dir", "WorldCenterX", "WorldCenterY", "Lat", "Lon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
