// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Vbs3GetPos.proto

#ifndef PROTOBUF_Vbs3GetPos_2eproto__INCLUDED
#define PROTOBUF_Vbs3GetPos_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace VBS3 {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Vbs3GetPos_2eproto();
void protobuf_AssignDesc_Vbs3GetPos_2eproto();
void protobuf_ShutdownFile_Vbs3GetPos_2eproto();

class Command;
class Position;

// ===================================================================

class Command : public ::google::protobuf::Message {
 public:
  Command();
  virtual ~Command();

  Command(const Command& from);

  inline Command& operator=(const Command& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Command& default_instance();

  void Swap(Command* other);

  // implements Message ----------------------------------------------

  Command* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Command& from);
  void MergeFrom(const Command& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string cmd = 1;
  inline bool has_cmd() const;
  inline void clear_cmd();
  static const int kCmdFieldNumber = 1;
  inline const ::std::string& cmd() const;
  inline void set_cmd(const ::std::string& value);
  inline void set_cmd(const char* value);
  inline void set_cmd(const char* value, size_t size);
  inline ::std::string* mutable_cmd();
  inline ::std::string* release_cmd();
  inline void set_allocated_cmd(::std::string* cmd);

  // @@protoc_insertion_point(class_scope:VBS3.Command)
 private:
  inline void set_has_cmd();
  inline void clear_has_cmd();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* cmd_;
  friend void  protobuf_AddDesc_Vbs3GetPos_2eproto();
  friend void protobuf_AssignDesc_Vbs3GetPos_2eproto();
  friend void protobuf_ShutdownFile_Vbs3GetPos_2eproto();

  void InitAsDefaultInstance();
  static Command* default_instance_;
};
// -------------------------------------------------------------------

class Position : public ::google::protobuf::Message {
 public:
  Position();
  virtual ~Position();

  Position(const Position& from);

  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Position& default_instance();

  void Swap(Position* other);

  // implements Message ----------------------------------------------

  Position* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Position& from);
  void MergeFrom(const Position& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);

  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);

  // required float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);

  // optional float deltaT = 4;
  inline bool has_deltat() const;
  inline void clear_deltat();
  static const int kDeltaTFieldNumber = 4;
  inline float deltat() const;
  inline void set_deltat(float value);

  // optional string id = 5;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 5;
  inline const ::std::string& id() const;
  inline void set_id(const ::std::string& value);
  inline void set_id(const char* value);
  inline void set_id(const char* value, size_t size);
  inline ::std::string* mutable_id();
  inline ::std::string* release_id();
  inline void set_allocated_id(::std::string* id);

  // required float dir = 6;
  inline bool has_dir() const;
  inline void clear_dir();
  static const int kDirFieldNumber = 6;
  inline float dir() const;
  inline void set_dir(float value);

  // required float worldCenterX = 7;
  inline bool has_worldcenterx() const;
  inline void clear_worldcenterx();
  static const int kWorldCenterXFieldNumber = 7;
  inline float worldcenterx() const;
  inline void set_worldcenterx(float value);

  // required float worldCenterY = 8;
  inline bool has_worldcentery() const;
  inline void clear_worldcentery();
  static const int kWorldCenterYFieldNumber = 8;
  inline float worldcentery() const;
  inline void set_worldcentery(float value);

  // optional string lat = 9;
  inline bool has_lat() const;
  inline void clear_lat();
  static const int kLatFieldNumber = 9;
  inline const ::std::string& lat() const;
  inline void set_lat(const ::std::string& value);
  inline void set_lat(const char* value);
  inline void set_lat(const char* value, size_t size);
  inline ::std::string* mutable_lat();
  inline ::std::string* release_lat();
  inline void set_allocated_lat(::std::string* lat);

  // optional string lon = 10;
  inline bool has_lon() const;
  inline void clear_lon();
  static const int kLonFieldNumber = 10;
  inline const ::std::string& lon() const;
  inline void set_lon(const ::std::string& value);
  inline void set_lon(const char* value);
  inline void set_lon(const char* value, size_t size);
  inline ::std::string* mutable_lon();
  inline ::std::string* release_lon();
  inline void set_allocated_lon(::std::string* lon);

  // @@protoc_insertion_point(class_scope:VBS3.Position)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_deltat();
  inline void clear_has_deltat();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_dir();
  inline void clear_has_dir();
  inline void set_has_worldcenterx();
  inline void clear_has_worldcenterx();
  inline void set_has_worldcentery();
  inline void clear_has_worldcentery();
  inline void set_has_lat();
  inline void clear_has_lat();
  inline void set_has_lon();
  inline void clear_has_lon();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  float x_;
  float y_;
  float z_;
  float deltat_;
  ::std::string* id_;
  float dir_;
  float worldcenterx_;
  ::std::string* lat_;
  ::std::string* lon_;
  float worldcentery_;
  friend void  protobuf_AddDesc_Vbs3GetPos_2eproto();
  friend void protobuf_AssignDesc_Vbs3GetPos_2eproto();
  friend void protobuf_ShutdownFile_Vbs3GetPos_2eproto();

  void InitAsDefaultInstance();
  static Position* default_instance_;
};
// ===================================================================


// ===================================================================

// Command

// required string cmd = 1;
inline bool Command::has_cmd() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Command::set_has_cmd() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Command::clear_has_cmd() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Command::clear_cmd() {
  if (cmd_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cmd_->clear();
  }
  clear_has_cmd();
}
inline const ::std::string& Command::cmd() const {
  // @@protoc_insertion_point(field_get:VBS3.Command.cmd)
  return *cmd_;
}
inline void Command::set_cmd(const ::std::string& value) {
  set_has_cmd();
  if (cmd_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cmd_ = new ::std::string;
  }
  cmd_->assign(value);
  // @@protoc_insertion_point(field_set:VBS3.Command.cmd)
}
inline void Command::set_cmd(const char* value) {
  set_has_cmd();
  if (cmd_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cmd_ = new ::std::string;
  }
  cmd_->assign(value);
  // @@protoc_insertion_point(field_set_char:VBS3.Command.cmd)
}
inline void Command::set_cmd(const char* value, size_t size) {
  set_has_cmd();
  if (cmd_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cmd_ = new ::std::string;
  }
  cmd_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:VBS3.Command.cmd)
}
inline ::std::string* Command::mutable_cmd() {
  set_has_cmd();
  if (cmd_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cmd_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:VBS3.Command.cmd)
  return cmd_;
}
inline ::std::string* Command::release_cmd() {
  clear_has_cmd();
  if (cmd_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = cmd_;
    cmd_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Command::set_allocated_cmd(::std::string* cmd) {
  if (cmd_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cmd_;
  }
  if (cmd) {
    set_has_cmd();
    cmd_ = cmd;
  } else {
    clear_has_cmd();
    cmd_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:VBS3.Command.cmd)
}

// -------------------------------------------------------------------

// Position

// required float x = 1;
inline bool Position::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Position::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Position::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Position::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Position::x() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.x)
  return x_;
}
inline void Position::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:VBS3.Position.x)
}

// required float y = 2;
inline bool Position::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Position::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Position::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Position::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Position::y() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.y)
  return y_;
}
inline void Position::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:VBS3.Position.y)
}

// required float z = 3;
inline bool Position::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Position::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Position::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Position::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Position::z() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.z)
  return z_;
}
inline void Position::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:VBS3.Position.z)
}

// optional float deltaT = 4;
inline bool Position::has_deltat() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Position::set_has_deltat() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Position::clear_has_deltat() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Position::clear_deltat() {
  deltat_ = 0;
  clear_has_deltat();
}
inline float Position::deltat() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.deltaT)
  return deltat_;
}
inline void Position::set_deltat(float value) {
  set_has_deltat();
  deltat_ = value;
  // @@protoc_insertion_point(field_set:VBS3.Position.deltaT)
}

// optional string id = 5;
inline bool Position::has_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Position::set_has_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Position::clear_has_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Position::clear_id() {
  if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_->clear();
  }
  clear_has_id();
}
inline const ::std::string& Position::id() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.id)
  return *id_;
}
inline void Position::set_id(const ::std::string& value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_ = new ::std::string;
  }
  id_->assign(value);
  // @@protoc_insertion_point(field_set:VBS3.Position.id)
}
inline void Position::set_id(const char* value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_ = new ::std::string;
  }
  id_->assign(value);
  // @@protoc_insertion_point(field_set_char:VBS3.Position.id)
}
inline void Position::set_id(const char* value, size_t size) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_ = new ::std::string;
  }
  id_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:VBS3.Position.id)
}
inline ::std::string* Position::mutable_id() {
  set_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    id_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:VBS3.Position.id)
  return id_;
}
inline ::std::string* Position::release_id() {
  clear_has_id();
  if (id_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = id_;
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Position::set_allocated_id(::std::string* id) {
  if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete id_;
  }
  if (id) {
    set_has_id();
    id_ = id;
  } else {
    clear_has_id();
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:VBS3.Position.id)
}

// required float dir = 6;
inline bool Position::has_dir() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Position::set_has_dir() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Position::clear_has_dir() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Position::clear_dir() {
  dir_ = 0;
  clear_has_dir();
}
inline float Position::dir() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.dir)
  return dir_;
}
inline void Position::set_dir(float value) {
  set_has_dir();
  dir_ = value;
  // @@protoc_insertion_point(field_set:VBS3.Position.dir)
}

// required float worldCenterX = 7;
inline bool Position::has_worldcenterx() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Position::set_has_worldcenterx() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Position::clear_has_worldcenterx() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Position::clear_worldcenterx() {
  worldcenterx_ = 0;
  clear_has_worldcenterx();
}
inline float Position::worldcenterx() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.worldCenterX)
  return worldcenterx_;
}
inline void Position::set_worldcenterx(float value) {
  set_has_worldcenterx();
  worldcenterx_ = value;
  // @@protoc_insertion_point(field_set:VBS3.Position.worldCenterX)
}

// required float worldCenterY = 8;
inline bool Position::has_worldcentery() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Position::set_has_worldcentery() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Position::clear_has_worldcentery() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Position::clear_worldcentery() {
  worldcentery_ = 0;
  clear_has_worldcentery();
}
inline float Position::worldcentery() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.worldCenterY)
  return worldcentery_;
}
inline void Position::set_worldcentery(float value) {
  set_has_worldcentery();
  worldcentery_ = value;
  // @@protoc_insertion_point(field_set:VBS3.Position.worldCenterY)
}

// optional string lat = 9;
inline bool Position::has_lat() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Position::set_has_lat() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Position::clear_has_lat() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Position::clear_lat() {
  if (lat_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lat_->clear();
  }
  clear_has_lat();
}
inline const ::std::string& Position::lat() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.lat)
  return *lat_;
}
inline void Position::set_lat(const ::std::string& value) {
  set_has_lat();
  if (lat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lat_ = new ::std::string;
  }
  lat_->assign(value);
  // @@protoc_insertion_point(field_set:VBS3.Position.lat)
}
inline void Position::set_lat(const char* value) {
  set_has_lat();
  if (lat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lat_ = new ::std::string;
  }
  lat_->assign(value);
  // @@protoc_insertion_point(field_set_char:VBS3.Position.lat)
}
inline void Position::set_lat(const char* value, size_t size) {
  set_has_lat();
  if (lat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lat_ = new ::std::string;
  }
  lat_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:VBS3.Position.lat)
}
inline ::std::string* Position::mutable_lat() {
  set_has_lat();
  if (lat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lat_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:VBS3.Position.lat)
  return lat_;
}
inline ::std::string* Position::release_lat() {
  clear_has_lat();
  if (lat_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = lat_;
    lat_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Position::set_allocated_lat(::std::string* lat) {
  if (lat_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete lat_;
  }
  if (lat) {
    set_has_lat();
    lat_ = lat;
  } else {
    clear_has_lat();
    lat_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:VBS3.Position.lat)
}

// optional string lon = 10;
inline bool Position::has_lon() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Position::set_has_lon() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Position::clear_has_lon() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Position::clear_lon() {
  if (lon_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lon_->clear();
  }
  clear_has_lon();
}
inline const ::std::string& Position::lon() const {
  // @@protoc_insertion_point(field_get:VBS3.Position.lon)
  return *lon_;
}
inline void Position::set_lon(const ::std::string& value) {
  set_has_lon();
  if (lon_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lon_ = new ::std::string;
  }
  lon_->assign(value);
  // @@protoc_insertion_point(field_set:VBS3.Position.lon)
}
inline void Position::set_lon(const char* value) {
  set_has_lon();
  if (lon_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lon_ = new ::std::string;
  }
  lon_->assign(value);
  // @@protoc_insertion_point(field_set_char:VBS3.Position.lon)
}
inline void Position::set_lon(const char* value, size_t size) {
  set_has_lon();
  if (lon_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lon_ = new ::std::string;
  }
  lon_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:VBS3.Position.lon)
}
inline ::std::string* Position::mutable_lon() {
  set_has_lon();
  if (lon_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    lon_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:VBS3.Position.lon)
  return lon_;
}
inline ::std::string* Position::release_lon() {
  clear_has_lon();
  if (lon_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = lon_;
    lon_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Position::set_allocated_lon(::std::string* lon) {
  if (lon_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete lon_;
  }
  if (lon) {
    set_has_lon();
    lon_ = lon;
  } else {
    clear_has_lon();
    lon_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:VBS3.Position.lon)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace VBS3

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Vbs3GetPos_2eproto__INCLUDED
